import torch
from torch import nn

# Simple convolutional discriminator for adversarial training of the VAE. 
# It takes a 128x128 grayscale image and outputs a single probability: real (1) or fake (0).
    #output: one number between 0 and 1 representing the probability that the input image is real (from the dataset) rather than fake (generated by the VAE). this is used to train the VAE to produce more realistic images by trying to fool the discriminator.
        # close to 1 → discriminator thinks it's real
        # close to 0 → discriminator thinks it's fake

class Discriminator(nn.Module):
    def __init__(self, in_channels: int = 1):
        super().__init__()

        self.net = nn.Sequential(
            # 128 → 64
            nn.Conv2d(in_channels, 32, kernel_size=4, stride=2, padding=1),
            nn.LeakyReLU(0.2, inplace=True), #to prevent dying neurons 

            # 64 → 32
            nn.Conv2d(32, 64, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(64),
            nn.LeakyReLU(0.2, inplace=True),

            # 32 → 16
            nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),

            # 16 → 8
            nn.Conv2d(128, 256, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2, inplace=True),

            # 8 → 4
            nn.Conv2d(256, 512, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(512),
            nn.LeakyReLU(0.2, inplace=True),

            # 4 → 1
            nn.Conv2d(512, 1, kernel_size=4, stride=1, padding=0),
            nn.Sigmoid()
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x).view(-1)  # (B,)